spring.application.name=

server.port=0
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.commonEntity.NotificationEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.group-id=notification-created-events

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# Dead Letter Topic configuration
spring.kafka.listener.dlt-publish=true
spring.kafka.listener.dlt-topic=notification-event-topic-dlt

spring.mail.host=smtp.gmail.com
spring.mail.port=587
sspring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
